FROM python:2.7.15

WORKDIR /src

ADD docker/entente-ci/install_container_dependencies.sh /tmp/
RUN /tmp/install_container_dependencies.sh
RUN rm /tmp/install_container_dependencies.sh

# Invalidate cache.
RUN echo 0.1.6 > /tmp/bump-version

# Copy requirements.txt separately so we can reuse the layer if the source
# code changes but the dependencies are the same.
COPY requirements_dev.txt requirements.txt /tmp/
RUN pip install --upgrade -r /tmp/requirements_dev.txt
#RUN rm -rf /root/.cache/pip
